### ISSUE TITLE
add gomod

### ISSUE THREAD

**Issue by jackielii** [pebbe/proj#2]
It doesn't seem to work in go modules, and also pkg.go.dev doesn't show docs: https://pkg.go.dev/github.com/pebbe/proj@v0.0.0-20190901113523-f366dc020b1f/v5?tab=overview

you also need to tag it with `git tag v5.0.0`

**Comment by pebbe** [comment]
I added a tag.

I don't think it needs go.mod, because it has no external dependencies (except for PROJ, but that is not Go)

**Comment by jackielii** [comment]
Thanks, I confirm it works with: `go get -u github.com/pebbe/proj/v5` Thanks again for maintaining this!
